// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuantityMeasurementAppRepositoryLayer.Context;

#nullable disable

namespace QuantityMeasurementAppRepositoryLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416054501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementAppModel.Entities.MeasurementRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesiredUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input1Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input1Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Input1Value")
                        .HasColumnType("float");

                    b.Property<string>("Input2Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input2Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Input2Value")
                        .HasColumnType("float");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("OriginalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginalValue")
                        .HasColumnType("float");

                    b.Property<string>("OutputText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OutputValue")
                        .HasColumnType("float");

                    b.Property<bool>("SuccessFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MeasurementRecords");
                });

            modelBuilder.Entity("QuantityMeasurementAppModel.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsGoogleUser")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
